/* build-logo.mjs — inline logo.svg into src/logo.js.
 *
 * The player is plain <script> tags with no bundler, so it can be opened straight
 * from disk with a double-click. file:// blocks fetch(), hence this tiny step:
 * the SVG becomes a string literal the page can read without a network request.
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');

const input = process.argv[2] ? resolve(process.cwd(), process.argv[2]) : resolve(root, 'logo.svg');
const output = resolve(root, 'src/logo.js');

if (!existsSync(input)) {
  console.error(`\n  Logo not found: ${input}\n`);
  console.error('  Save the reference logo as logo-animation/logo.svg, then re-run.');
  console.error('  It must be a real vector SVG with type converted to outlines.\n');
  process.exit(1);
}

let svg = readFileSync(input, 'utf8');

if (!/<svg[\s>]/i.test(svg)) {
  console.error(`\n  ${input} does not contain an <svg> element.\n`);
  process.exit(1);
}

// Strip anything that would fight the renderer or drag in a network request.
svg = svg
  .replace(/<\?xml[\s\S]*?\?>/gi, '')
  .replace(/<!DOCTYPE[\s\S]*?>/gi, '')
  .replace(/<!--[\s\S]*?-->/g, '')
  .replace(/<script[\s\S]*?<\/script>/gi, '')
  .trim();

const external = svg.match(/(?:href|src)\s*=\s*["'](?!#)(https?:|\/\/)[^"']*["']/gi);
if (external) {
  console.warn(`  ! ${external.length} external reference(s) in the SVG will not load offline.`);
}

const escaped = svg.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');

writeFileSync(
  output,
  '/* Generated by scripts/build-logo.mjs — do not edit. Source: ' +
    input.replace(root + '/', '') + ' */\n' +
    'window.LOGO_SVG = `' + escaped + '`;\n',
  'utf8'
);

const shapes = (svg.match(/<(path|rect|circle|ellipse|polygon|polyline|line)[\s>]/gi) || []).length;
const texts = (svg.match(/<text[\s>]/gi) || []).length;

console.log(`  logo.js written — ${shapes} drawable shape(s) from ${input.replace(root + '/', '')}`);
if (texts) {
  console.warn(`  ! ${texts} live <text> element(s) found. Convert type to outlines:`);
  console.warn('    live text has no path data, cannot be traced, and will not');
  console.warn('    render identically on a machine without the font.');
}
if (!shapes) {
  console.error('  ! No drawable shapes found — the animation will have nothing to build.');
  process.exit(1);
}
